services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: sync+restart
          path: ./frontend/index.html
          target: /app/index.html
        - action: sync+restart
          path: ./frontend/vite.config.ts
          target: /app/vite.config.ts
        - action: sync+restart
          path: ./frontend/tsconfig.json
          target: /app/tsconfig.json
        - action: sync+restart
          path: ./frontend/tsconfig.app.json
          target: /app/tsconfig.app.json
        - action: sync+restart
          path: ./frontend/tsconfig.node.json
          target: /app/tsconfig.node.json
        - action: sync+restart
          path: ./frontend/env.d.ts
          target: /app/env.d.ts
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
    restart: always

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
      target: dev
    container_name: api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./API/src
          target: /app/src
        - action: sync+restart
          path: ./API/tsconfig.json
          target: /app/tsconfig.json
        - action: rebuild
          path: ./API/package.json
        - action: rebuild
          path: ./API/package-lock.json
    restart: always


  db:
    image: postgres:15
    container_name: DB
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
