services:

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
      target: dev
    container_name: api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    develop:
      watch:
        - action: sync
          path: ./API/src
          target: /app/src
        - action: sync+restart
          path: ./API/tsconfig.json
          target: /app/tsconfig.json
        - action: rebuild
          path: ./API/package.json
        - action: rebuild
          path: ./API/package-lock.json
    restart: always


  db:
    image: postgres:15
    container_name: DB
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
